_wandb:
    value:
        cli_version: 0.21.4
        e:
            ffh1jzjdmhzwspeb8jsqye6dhvtp88wj:
                args:
                    - --dataset_path
                    - /home/yifeng/workspace/training_data/2025-challenge-demos-task0006
                    - --filter_state
                    - --batch_size
                    - "32"
                    - --max_steps
                    - "100000"
                    - --save_steps
                    - "5000"
                    - --chunk_size
                    - "50"
                    - --num_workers
                    - "0"
                    - --lr
                    - "1e-4"
                    - --video_tolerance
                    - "0.15"
                    - --wandb_project
                    - b1k-smolvla-task0006
                codePath: train_smolvla_lerobot.py
                codePathLocal: train_smolvla_lerobot.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1005867986944"
                        used: "663750524928"
                email: wuyifeng5@gmail.com
                executable: /home/yifeng/miniconda3/envs/lerobot/bin/python
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-9729d7fc-8842-e1fa-e645-55e9439921b0
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-d3a7aa21-691a-33e2-9585-249bdc7ccd31
                host: Purrticle2
                memory:
                    total: "134724550656"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/yifeng/workspace/smolvla_training/train_smolvla_lerobot.py
                python: CPython 3.10.18
                root: /home/yifeng/workspace/smolvla_training
                startedAt: "2025-11-08T07:08:16.214836Z"
                writerId: ffh1jzjdmhzwspeb8jsqye6dhvtp88wj
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.4
            "6": 4.57.1
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 32
chunk_size:
    value: 50
dataset_path:
    value: /home/yifeng/workspace/training_data/2025-challenge-demos-task0006
device:
    value: cuda
filter_state:
    value: true
freeze_vision:
    value: false
gpu_id:
    value: 0
lr:
    value: 0.0001
max_steps:
    value: 100000
num_workers:
    value: 0
output_dir:
    value: ./outputs/train/smolvla_behavior
pretrained_model:
    value: lerobot/smolvla_base
repo_id:
    value: null
save_steps:
    value: 5000
video_tolerance:
    value: 0.15
wandb_disable:
    value: false
wandb_project:
    value: b1k-smolvla-task0006
